### ISSUE TITLE
Killswitch without LAN subnets is preventing DNS resolution

### ISSUE THREAD

**Issue by citrixscu** [yacht7/docker-openvpn-client#1]
Trying to get this working with Mullvad but the connections time out. Error log:

RESOLVE: Cannot resolve host address: us-nyc-xyz.mullvad.net:1196 (Try again)
Could not determine IPv4/IPv6 protocol
SIGUSR1[soft,init_instance] received, process restarting
Restart pause, 5 second(s)

The script will iterate through all of the remotes with the same error messages.

**Comment by yacht7** [comment]
@citrixscu are you using the latest image? I'm not sure when you pulled, but at one point I did have an issue where I was creating the killswitch too soon and not allowing resolution of the VPN server addresses.

**Comment by citrixscu** [comment]
I pulled both yesterday. One from Docker hub and the other I built from git clone.

**Comment by yacht7** [comment]
Can I see the OpenVPN config file with any sensitive bits removed and the output of `docker logs` after the errors?

**Comment by citrixscu** [comment]
vpn.conf --> https://pastebin.com/s0JjpiqY
logs --> https://pastebin.com/38TfPEsi

I've noticed that mullvad likes to use update-resolv-conf as the openvpn up and down scripts in its conf files, which I think requires openresolv.  Entry.sh overwrites this with /etc/openvpn/up, down. Forcing openvpn to use update-resolv-conf results in the same error.

**Comment by yacht7** [comment]
The changes in `entry.sh` are required by Alpine, and I've been running this image for a couple months now with no real problems. I would have expected to see issues with those changes before now. It's also worth mentioning that I've compared your config file to mine (I also use Mullvad), and they are nearly identical. I even used the same addresses as you and successfully connected.

What's interesting to me is the addresses _are_ being resolved during the creation of the killswitch. However, once the killswitch is in place and the VPN tries to connect, it fails to resolve. This does not happen on my end.

Can you try running a container with `LOG_LEVEL` set to `7` instead of the default `3`? I'm interested in that output as well.

**Comment by citrixscu** [comment]
Here you go. 

https://pastebin.com/E2sKaFwe

**Comment by yacht7** [comment]
I think I see what the problem is. Try adding your LAN network range with the `SUBNETS` option. I'm able to reproduce the error if I remove that from my container configuration.

Let me know if this works for you.

**Comment by citrixscu** [comment]
Confirming this works. Thank you.

**Comment by yacht7** [comment]
No problem!

So I don't have to figure this out again in the future, I'm adding a to-do for myself:
- [ ] Add a note about the killswitch affecting DNS resolution if LAN subnets are not specified (or not done properly).

**Comment by citrixscu** [comment]
Sounds good. Thanks for your work. Now that wireguard is part of the linux kernel, I wonder if much of this could be reused to set up a wireguard tunnel rather than ovpn.

**Comment by yacht7** [comment]
Definitely something I'm going to look into. The killswitch will likely be reusable which is good because that was the trickiest part.

**Comment by orsa86** [comment]
Hi,

I have the same issue. The image is created using git clone and git build.
Adding "SUBNETS" and even "FORWARDED_PORTS" didn't help in my case. I also
tried to add docker network to subnets and exposing port 1302.

This is env file:

SUBNETS=192.168.5.0/24,172.18.0.0/24
FORWARDED_PORTS=1302

The logs with level 7:

https://pastebin.com/EhrJEjBv

It seems to me that resolv.conf is not properly updated in my case.
This is how it looks after container is started.

/etc/openvpn # cat /etc/resolv.conf
nameserver 127.0.0.11
options ndots:0

And this is how up.sh is executed (set -xe):

/etc/openvpn # ./up.sh
+ '['  '!=' no ]
+ NS=
+ DOMAIN=
+ SEARCH=
+ i=1
+ true
+ eval 'opt=$foreign_option_1'
+ opt=
+ '[' -z  ]
+ break
+ '[' -n  ]
+ '[' -n  ]
+ exit 0

Thanks for help!

**Comment by yacht7** [comment]
@orsa86 Is the DNS on the underlying host configured to go to a server in `192.168.5.0/24`?

For example, my underlying host's IP is `192.168.10.10`. Its primary DNS server is `192.168.10.1`. Is yours configured like this or does it point directly to an external DNS server like `1.1.1.1` or `8.8.8.8`?

As you've seen, adding `FORWARDED_PORTS`, adding the Docker network to `SUBNETS`, and/or exposing ports won't affect anything here. Just wanted to keep you from barking up the wrong tree.

**Comment by orsa86** [comment]
@yacht7 thanks for the hint. It works now. I'm running arch linux arm on rpi4 (192.168.5.60) and am using pihole in docker container. Since pihole needs port 53 I had to disable systemd-resolved. The entry in resolv.conf was pointing to the address of the host itself (192.168.5.60). I changed this address to my router/dns ip address and disabled pihole container, so it works now. Now I only need to figure out what is valid configuration to run it all together.

**Comment by yacht7** [comment]
Basically, your underlying host's DNS server needs to be included in `SUBNETS` for resolution to work properly before the VPN is connected. I'm not sure how/why Pi-hole is affecting this.

I wouldn't think using a DNS forwarder on the same host would cause any problems.

**Comment by dausruddin** [comment]
> @wfg Is yours configured like this or does it point directly to an external DNS server like 1.1.1.1 or 8.8.8.8?

Hi. I am using external DNS like you mentioned. What should I do to make this work? I tried adding `SUBNETS=8.8.8.8/32,8.8.4.4/32`, but still it cannot resolve VPN server I am using.

**Comment by peter17** [comment]
@wfg Sorry to bother, but I have the same question as just above: how would you do to use 1.1.1.1 as the DNS server?
If it is possible, could you please add an example in the documentation?
Thanks a lot in advance! Best regards
